# OBEX P2 Display Manifest
version: "1.0"
last_updated: "2025-09-12"
category: "display"
description: "P2 display drivers and graphics interfaces from OBEX community"

metadata:
  total_objects: 17
  quality_range: "6-9"
  
subcategories:
  led_matrix:
    description: "LED matrix and RGB panel drivers"
    object_count: 6
    
  lcd_interfaces:
    description: "Character and graphic LCD drivers"
    object_count: 5
    
  vga_graphics:
    description: "VGA and video output drivers"
    object_count: 4
    
  oled_displays:
    description: "OLED and small display interfaces"
    object_count: 2

objects: {}

ai_usage_notes: |
  Display drivers handle visual output for P2 systems.
  Consider resolution, refresh rate, and cog requirements.