category: cog_control
description: Cog and hub control
instruction_count: 11
base_path: engineering/knowledge-base/P2/language/pasm2/
instructions:
- name: brk
  content: brk.yaml
  desc: BRK triggers a breakpoint in the current cog and either defines a breakpoint
    code or the next bre...
- name: cogbrk
  content: cogbrk.yaml
  desc: COGBRK triggers an asynchronous breakpoint in a designated cog. The COGBRK
    instruction must be ex...
- name: cogid
  content: cogid.yaml
  desc: COGID writes the current cog's ID into Dest (if Dest is a register and WC
    is omitted) or sets/cle...
- name: coginit
  content: coginit.yaml
  desc: COGINIT starts a new (unused) cog, a new pair of cogs (that may share LUT
    memory), or a specific ...
- name: cogstop
  content: cogstop.yaml
  desc: COGSTOP terminates the cog identified by Dest[2:0]. In this dormant state,
    the cog ceases to exec...
- name: fblock
  content: fblock.yaml
  desc: Set next block for when block wraps. D[13:0] = block size in 64-byte units
    (0 = max), S[19:0] = b...
- name: getbrk
  content: getbrk.yaml
  desc: Get breakpoint/cog status into D according to WC/WZ/WCZ.  Flag modes determine
    what information i...
- name: hubset
  content: hubset.yaml
  desc: Set hub configuration to D.                                                                       ...
- name: locknew
  content: locknew.yaml
  desc: '{WC}   Request a LOCK. D will be written with the LOCK number (0 to 15).
    C = 1 if no LOCK availab...'
- name: lockrel
  content: lockrel.yaml
  desc: Release LOCK D[3:0]. If D is a register and WC, get current/last cog id of
    LOCK owner into D and ...
- name: locktry
  content: locktry.yaml
  desc: Try to acquire lock D[3:0]. C = 1 if got LOCK.  P2 provides 16 hardware locks
    (0-15) for inter-CO...
