category: colorspace
description: Pixel and colorspace operations
instruction_count: 7
base_path: engineering/knowledge-base/P2/language/pasm2/
instructions:
- name: blnpix
  content: blnpix.yaml
  desc: Alpha-blend bytes of S into bytes of D, using SETPIV value.
- name: mixpix
  content: mixpix.yaml
  desc: Mix bytes of S into bytes of D, using SETPIX and SETPIV values.
- name: setcfrq
  content: setcfrq.yaml
  desc: Set the colorspace converter \"CFRQ\" parameter to D[31:0].
- name: setci
  content: setci.yaml
  desc: Set the colorspace converter \"CI\" parameter to D[31:0].
- name: setcmod
  content: setcmod.yaml
  desc: Set the colorspace converter \"CMOD\" parameter to D[8:0].
- name: setcq
  content: setcq.yaml
  desc: Set the colorspace converter \"CQ\" parameter to D[31:0].
- name: setcy
  content: setcy.yaml
  desc: Set the colorspace converter \"CY\" parameter to D[31:0].
