category: control_flow
description: Branches, jumps, and calls
instruction_count: 27
base_path: engineering/knowledge-base/P2/language/pasm2/
instructions:
- name: call
  content: call.yaml
  desc: CALL records the current state of the C and Z flags and the address of the
    next instruction (PC +...
- name: calla
  content: calla.yaml
  desc: Write current C and Z flags and address of the next instruction into the 4-byte
    Hub RAM location ...
- name: callb
  content: callb.yaml
  desc: Write current C and Z flags and address of the next instruction into the 4-byte
    Hub RAM location ...
- name: calld
  content: calld.yaml
  desc: CALLD records the current state of the C and Z flags and the address of the
    next instruction (PC ...
- name: callpa
  content: callpa.yaml
  desc: CALLPA and CALLPB records the current state of the C and Z flags and the address
    of the next inst...
- name: callpb
  content: callpb.yaml
  desc: CALLPA and CALLPB records the current state of the C and Z flags and the address
    of the next inst...
- name: djnz
  content: djnz.yaml
  desc: DJZ or DJNZ decrements the value in Dest, writes the result, and jumps to
    the address described b...
- name: djz
  content: djz.yaml
  desc: DJZ or DJNZ decrements the value in Dest, writes the result, and jumps to
    the address described b...
- name: execf
  content: execf.yaml
  desc: 'Jump to D[9:0] in cog/LUT and set SKIPF pattern to D[31:10]. PC = {10''b0,
    D[9:0]}. '
- name: ijnz
  content: ijnz.yaml
  desc: IJZ or IJNZ increments the value in Dest, writes the result, and jumps to
    the address described b...
- name: ijz
  content: ijz.yaml
  desc: IJZ or IJNZ increments the value in Dest, writes the result, and jumps to
    the address described b...
- name: jmp
  content: jmp.yaml
  desc: Jump to A. If R = 1 then PC += A, else PC = A. "\" forces R = 0.
- name: jmprel
  content: jmprel.yaml
  desc: Jump ahead/back by D instructions. For cogex, PC += D[19:0]. For hubex, PC
    += D[17:0] << 2.
- name: lockret
  content: lockret.yaml
  desc: Return LOCK D[3:0] for reallocation.                                                             ...
- name: rep
  content: rep.yaml
  desc: Execute next D[8:0] instructions S times. If S = 0, repeat instructions infinitely.
    If D[8:0] = 0,...
- name: ret
  content: ret.yaml
  desc: Return by popping stack (K). C = K[31], Z = K[30], PC = K[19:0].
- name: reta
  content: reta.yaml
  desc: Return by reading hub long (L) at --PTRA. C = L[31], Z = L[30], PC = L[19:0].                    ...
- name: retb
  content: retb.yaml
  desc: Return by reading hub long (L) at --PTRB. C = L[31], Z = L[30], PC = L[19:0].                    ...
- name: reti0
  content: reti0.yaml
  desc: Return from INT0. (CALLD $1FF,$1FF WCZ).
- name: reti1
  content: reti1.yaml
  desc: Return from INT1. (CALLD $1FF,$1F5 WCZ).
- name: reti2
  content: reti2.yaml
  desc: Return from INT2. (CALLD $1FF,$1F3 WCZ).
- name: reti3
  content: reti3.yaml
  desc: Return from INT3. (CALLD $1FF,$1F1 WCZ).
- name: skip
  content: skip.yaml
  desc: Skip instructions per D. Subsequent instructions 0..31 get cancelled for each
    '1' bit in D[0]..D[...
- name: skipf
  content: skipf.yaml
  desc: Skip cog/LUT instructions fast per D. Like SKIP, but instead of cancelling
    instructions, the PC l...
- name: tjf
  content: tjf.yaml
  desc: Test D and jump to S** if D is full (D = $FFFF_FFFF).                                            ...
- name: tjnz
  content: tjnz.yaml
  desc: Dest is tested and if it's zero (or not zero in syntax 2), PC is set to a
    new relative (#Src) or ...
- name: tjz
  content: tjz.yaml
  desc: Test D and jump to S** if D is zero.                                                             ...
