category: special_ops
description: Special operations and modifiers
instruction_count: 35
base_path: engineering/knowledge-base/P2/language/pasm2/
instructions:
- name: altb
  content: altb.yaml
  desc: ALTB should be followed by a BITxxx instruction— it modifies the BITxxx instruction's
    Dest value,...
- name: altd
  content: altd.yaml
  desc: ALTD modifies the next instruction's Dest value to be (Src + Dest) & $1FF
    (for syntax 1), or to D...
- name: altgb
  content: altgb.yaml
  desc: ALTGB should be followed by GETBYTE or ROLBYTE— it modifies the GETBYTE /
    ROLBYTE instruction's S...
- name: altgn
  content: altgn.yaml
  desc: ALTGN should be followed by GETNIB or ROLNIB— it modifies the GETNIB / ROLNIB
    instruction's Src a...
- name: altgw
  content: altgw.yaml
  desc: ALTGW should be followed by GETWORD or ROLWORD— it modifies the GETWORD /
    ROLWORD instruction's S...
- name: alti
  content: alti.yaml
  desc: ALTI substitutes fields from Dest for one or more of the next instruction's
    pipelined Dest, Src, ...
- name: altr
  content: altr.yaml
  desc: ALTR modifies the next instruction's Result address to be (Src + Dest) & $1FF
    (for syntax 1), or ...
- name: alts
  content: alts.yaml
  desc: ALTS modifies the next instruction's Src value to be (Src + Dest) & $1FF (for
    syntax 1), or to De...
- name: altsb
  content: altsb.yaml
  desc: ALTSB should be followed by SETBYTE— it modifies the SETBYTE instruction's
    Dest and Num values, e...
- name: altsn
  content: altsn.yaml
  desc: ALTSN should be followed by SETNIB— it modifies the SETNIB instruction's Dest
    and Num values, ena...
- name: altsw
  content: altsw.yaml
  desc: ALTSW should be followed by SETWORD— it modifies the SETWORD instruction's
    Dest and Num values, e...
- name: augd
  content: augd.yaml
  desc: AUGD is an assistant instruction to aid with literal values that exceed 9
    bits. Most PASM2 instru...
- name: augs
  content: augs.yaml
  desc: AUGS is an assistant instruction to aid with literal values that exceed 9
    bits. Most PASM2 instru...
- name: debug
  content: debug.yaml
  desc: Debug instruction. Provides debugging functionality during program execution.
- name: getptr
  content: getptr.yaml
  desc: Get current FIFO hub pointer into D.                                                             ...
- name: getrnd
  content: getrnd.yaml
  desc: Get RND into C/Z. C = RND[31], Z = RND[30], unique per cog.
- name: getscp
  content: getscp.yaml
  desc: Get four-channel oscilloscope samples into D. D = {ch3[7:0],ch2[7:0],ch1[7:0],ch0[7:0]}.
- name: loc
  content: loc.yaml
  desc: R = 1, address = PC + A, else address = A.
- name: mergeb
  content: mergeb.yaml
  desc: Merge bits of bytes in D. D = {D[31], D[23], D[15], D[7], ...D[24], D[16],
    D[8], D[0]}.
- name: mergew
  content: mergew.yaml
  desc: Merge bits of words in D. D = {D[31], D[15], D[30], D[14], ...D[17], D[1],
    D[16], D[0]}.
- name: modc
  content: modc.yaml
  desc: MODC, MODZ, or MODCZ sets or clears the C and/or Z flag based on the mode
    described by the given ...
- name: modcz
  content: modcz.yaml
  desc: MODC, MODZ, or MODCZ sets or clears the C and/or Z flag based on the mode
    described by the given ...
- name: modz
  content: modz.yaml
  desc: MODC, MODZ, or MODCZ sets or clears the C and/or Z flag based on the mode
    described by the given ...
- name: nop
  content: nop.yaml
  desc: 'NOP simply consumes two clock cycles; no other operation is performed. Result:
    Two clock cycles a...'
- name: setluts
  content: setluts.yaml
  desc: If D[0] = 1 then enable LUT sharing, where LUT writes within the adjacent
    odd/even companion cog ...
- name: setpat
  content: setpat.yaml
  desc: Set pin pattern for PAT event. C selects INA/INB, Z selects =/!=, D provides
    mask value, S provid...
- name: setpiv
  content: setpiv.yaml
  desc: Set BLNPIX/MIXPIX blend factor to D[7:0].
- name: setpix
  content: setpix.yaml
  desc: Set MIXPIX mode to D[5:0].
- name: setq
  content: setq.yaml
  desc: Set Q to D. Use before RDLONG/WRLONG/WMLONG to set block transfer. Also used
    before MUXQ/COGINIT/...
- name: setq2
  content: setq2.yaml
  desc: Set Q to D. Use before RDLONG/WRLONG/WMLONG to set LUT block transfer.  SETQ2
    enables block trans...
- name: setr
  content: setr.yaml
  desc: SETR copies Src[8:0] to the Result field of the template, Dest, to be used
    with an ALTI instructi...
- name: seussf
  content: seussf.yaml
  desc: Relocate and periodically invert bits within D. Returns to original value
    on 32nd iteration. Forw...
- name: seussr
  content: seussr.yaml
  desc: Relocate and periodically invert bits within D. Returns to original value
    on 32nd iteration. Reve...
- name: splitb
  content: splitb.yaml
  desc: Split every 4th bit of D into bytes. D = {D[31], D[27], D[23], D[19], ...D[12],
    D[8], D[4], D[0]}.
- name: splitw
  content: splitw.yaml
  desc: Split odd/even bits of D into words. D = {D[31], D[29], D[27], D[25], ...D[6],
    D[4], D[2], D[0]}.
