category: stack_ops
description: Stack operations
instruction_count: 6
base_path: engineering/knowledge-base/P2/language/pasm2/
instructions:
- name: pop
  content: pop.yaml
  desc: Pop value from internal hardware stack (8-level)
- name: popa
  content: popa.yaml
  desc: Read long from hub address --PTRA into D.
- name: popb
  content: popb.yaml
  desc: Read long from hub address --PTRB into D.
- name: pusha
  content: pusha.yaml
  desc: Write long in D[31:0] to hub address PTRA++.
- name: push
  content: push.yaml
  desc: Push value onto internal hardware stack (8-level)
- name: pushb
  content: pushb.yaml
  desc: Write long in D[31:0] to hub address PTRB++.
