category: streamer
description: Streamer operations
instruction_count: 6
base_path: engineering/knowledge-base/P2/language/pasm2/
instructions:
- name: getxacc
  content: getxacc.yaml
  desc: Get the streamer's Goertzel X accumulator into D and the Y accumulator into
    the next instruction'...
- name: setxfrq
  content: setxfrq.yaml
  desc: Set streamer NCO frequency to D.
- name: xcont
  content: xcont.yaml
  desc: Bu er new streamer command to be issued on final NCO rollover of current command,
    continuing phase...
- name: xinit
  content: xinit.yaml
  desc: Issue streamer command immediately, zeroing phase.
- name: xstop
  content: xstop.yaml
  desc: Stop streamer immediately.
- name: xzero
  content: xzero.yaml
  desc: Bu er new streamer command to be issued on final NCO rollover of current command,
    zeroing phase.  ...
