manifest_metadata:
  manifest_type: obex_author
  author: Charles Current
  generated: 2025-09-12T16:10:0
  object_count: 1
author_info:
  name: Charles Current
  contribution_summary: 1 P2 objects contributed to OBEX
  specialties:
  - drivers (1 objects)
  - SPIN2 (1)
objects:
- object_id: '2859'
  title: nextion_ez
  category: drivers
  languages:
  - SPIN2
  created_date: '2023-11-16 20:08:18'
  yaml_path: ../objects/2859.yaml
