manifest_metadata:
  manifest_type: obex_author
  author: evanh
  generated: 2025-09-12T16:10:0
  object_count: 2
author_info:
  name: evanh
  contribution_summary: 2 P2 objects contributed to OBEX
  specialties:
  - misc (2 objects)
  - SPIN2 (2)
objects:
- object_id: '3804'
  title: Pllset
  category: misc
  languages:
  - SPIN2
  created_date: '2024-03-06 07:31:45'
  yaml_path: ../objects/3804.yaml
- object_id: '4442'
  title: 8-bit SAR ADC
  category: misc
  languages:
  - SPIN2
  created_date: '2024-03-06 09:26:57'
  yaml_path: ../objects/4442.yaml
