manifest_metadata:
  manifest_type: obex_author
  author: MagIO2
  generated: 2025-09-12T16:10:0
  object_count: 1
author_info:
  name: MagIO2
  contribution_summary: 1 P2 objects contributed to OBEX
  specialties:
  - drivers (1 objects)
  - SPIN2 (1)
  - PASM2 (1)
objects:
- object_id: '2848'
  title: Graphics Display Driver Architecture
  category: drivers
  languages:
  - SPIN2
  - PASM2
  created_date: '2021-04-10 12:00:00'
  yaml_path: ../objects/2848.yaml
