manifest_metadata:
  manifest_type: obex_author
  author: ManAtWork
  generated: 2025-09-12T16:10:0
  object_count: 4
author_info:
  name: ManAtWork
  contribution_summary: 4 P2 objects contributed to OBEX
  specialties:
  - motors (2 objects)
  - SPIN2 (4)
  - PASM2 (3)
objects:
- object_id: '2811'
  title: Park transformation
  category: motors
  languages:
  - SPIN2
  - PASM2
  created_date: '2020-05-09 12:00:00'
  yaml_path: ../objects/2811.yaml
- object_id: '2872'
  title: Simple SPI flash driver
  category: drivers
  languages:
  - SPIN2
  created_date: '2020-07-07 12:00:00'
  yaml_path: ../objects/2872.yaml
- object_id: '4267'
  title: Ethernet RMII driver
  category: drivers
  languages:
  - SPIN2
  - PASM2
  created_date: '2024-02-26 16:21:51'
  yaml_path: ../objects/4267.yaml
- object_id: '4918'
  title: Step/Dir signal generator
  category: motors
  languages:
  - SPIN2
  - PASM2
  created_date: '2024-11-13 13:50:52'
  yaml_path: ../objects/4918.yaml
